#!/bin/sh

eloc='srm://fndca1.fnal.gov:8443/pnfs/fnal.gov/usr/'
for f in "$@"
do
   flocs=`ifdh locateFile $f`
   eflocs=`echo "$flocs" | grep enstore: | head -1`
   bflocs=`echo "$flocs" | grep _bluearc: | head -1`
   if [ x$eflocs != x ]
   then
       echo "found file on enstore, using dcache srm"
       src="`echo $eflocs |
	      sed -e "s;enstore:/pnfs/;$eloc;" -e 's/(.*//'`/$f"
   else
       echo "found file on bluearc"
       src="`echo $bflocs | head -1 | sed -e 's/.*_bluearc://'`/$f"
   fi
   echo "doing:" ifdh cp "$src"  "./$f" 
   ifdh cp "$src"  "./$f"
done

