#!/bin/sh

usage() {
cat >&2 <<EOF
   usage: 
      $0 [-e experiment] filename1 filename2 ...
          find files in SAM and ifdh cp them here
      $0 [-e experiment] --dims "dimension-string"
          find files in SAM by dimension string and ifdh cp them here
      $0 --help
          print this message to stderr
EOF
}

case `df . | tail -1` in
*/app) size=`echo "$@" | wc -w`
         if [ $size -gt 10 ]
         then
             echo "Sorry, this utility won't copy large datasets to the /experiment/app areas" >& 2
             exit 1
         else
             echo "Notice: copying data to /experiment/app areas is not recommended." >&2
             echo "...but since it's only a few files, copying via /tmp"
         fi
         dest='/tmp/$f'
         extra='; cp /tmp/$f ./$f; rm /tmp/$f'
         ;;
*)       dest='./$f'
         extra=''
esac

while :
do
case x$1 in 

x--prestage)
    shift
    dest='/dev/null'
    ;;
    
x--dims)
    dims="$2"
    shift
    shift
    set : "$@" `ifdh translateConstraints "$dims"`
    shift
    continue
    ;;
x--help)
    usage
    exit 0
    ;;
x-e)
    export EXPERIMENT=$2
    shift
    shift
    ;;
x)  usage
    exit 1
    ;;
*)  break
    ;;
esac
done

case x$EXPERIMENT in
x) echo "Need EXPERIMENT set in the environment" >&2
   exit 1
   ;;
*) ;;
esac

for f in "$@"
do
   flocs=`ifdh locateFile $f`
   eflocs=`echo "$flocs" | grep enstore: | head -1`
   bflocs=`echo "$flocs" | egrep '(_bluearc|data):' | head -1`
   if [ x$eflocs != x ]
   then
       echo "found file on enstore, using dcache srm"

       src="`echo $eflocs |
	      sed -e "s/enstore://" -e 's/(.*//'`/$f"
   else
       echo "found file on bluearc"
       src="`echo $bflocs |  perl -pe 's/.*(_bluearc|data)://;'`/$f"
   fi
   eval "cmd='ifdh cp \"$src\"  \"$dest\" $extra'"
   echo "doing:"  $cmd
   eval $cmd
done

